---
- name: Setup Infrastructure
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name:  Create VPC in AWS
      ec2_vpc_net:
        profile: default
        region: us-east-1
        state: present
        cidr_block: '42.0.0.0/16'
        name: "minimal-ghost-blog"
        tags: {"Environment": "minimal-ghost-blog"}
      register: vpc_result

    - name: Create IGW for minimal-ghost-blog
      ec2_vpc_igw:
        profile: default
        region: us-east-1
        state: present
        vpc_id: "{{vpc_result.vpc.id}}"
      register: igw

    - name: Create VPC Subnet for minimal-ghost-blog
      ec2_vpc_subnet:
        profile: default
        region: us-east-1
        state: present
        az: us-east-1a
        cidr: '42.0.0.0/24'
        tags: { "Name": "minimal-ghost-blog-subnet", "Environment":"minimal-ghost-blog", "Type": "public" }
        vpc_id: "{{vpc_result.vpc.id}}"
      register: subnet_result

    - name: Set up routing table for public subnet
      ec2_vpc_route_table:
        profile: default
        region: us-east-1
        state: present
        vpc_id: "{{vpc_result.vpc.id}}"
        subnets:
          - "{{subnet_result.subnet.id}}"
        routes:
          - dest: '0.0.0.0/0'
            gateway_id: igw
        tags: { "Name": "minimal-ghost-blog-public", "Type": "public", "Environment": "minimal-ghost-blog"}

    - name: Create Security group
      ec2_group:
        name: ghost_blog_sg
        description: Allows http/https/ssh to machine from anywhere
        vpc_id: "{{vpc_result.vpc.id}}"
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: '0.0.0.0/0'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: '0.0.0.0/0'
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: '0.0.0.0/0'

    - name: Launch an Ubuntu EC2 instance
      ec2:
        profile: default
        region: us-east-1
        key_name: ghost-blog
        group: ghost_blog_sg
        instance_type: t2.micro
        image: ami-cd0f5cb6
        wait: true
        vpc_subnet_id: "{{subnet_result.subnet.id}}"
        assign_public_ip: yes
        instance_tags:  '{"Name":"minimal-ghost-blog"}'
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Set New IP fact
      set_fact:
        ghost_blog_ip: "{{ ec2.instances | map(attribute='public_dns_name') |first }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ghost_blog_ip}}"
        groupname: launched

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Setup Ghost on Launched Instance
  hosts: launched
  become: True
  remote_user: ubuntu
  gather_facts: False
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - ghost_install
  